/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rmit.se2.pkg2012a.skoorti.view.panel;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Observable;
import java.util.Observer;
import rmit.se2.pkg2012a.skoorti.GameEngine;
import rmit.se2.pkg2012a.skoorti.model.util.Logable;
import rmit.se2.pkg2012a.skoorti.model.util.Mediator;

/**
 *
 * @author zozo
 */
public class LogPanel extends javax.swing.JPanel {
    private GameEngine gameEngine;
    /**
     * Creates new form LogPanel
     */
    public LogPanel(GameEngine gameEngine) {
        initComponents();
        this.gameEngine = gameEngine;
        
        Mediator.subscribe("game:log", new Observer() {
            @Override
            public void update(Observable o, Object obj) {
                if (obj instanceof Logable) {
                    updateLog((Logable)obj);
                }
            }
        });
    }
    
    private void updateLog(Logable obj) {
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        String currentDate = dateFormat.format(date);
        String current = this.logArea.getText();
        current = currentDate + " : " + obj.log() + "\n" + current;
        this.logArea.setText(current);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        logArea = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        logArea.setColumns(10);
        logArea.setEditable(false);
        logArea.setRows(10);
        logArea.setBorder(javax.swing.BorderFactory.createTitledBorder("Game Logs"));
        jScrollPane1.setViewportView(logArea);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea logArea;
    // End of variables declaration//GEN-END:variables
}
