/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rmit.se2.pkg2012a.skoorti.view.panel;

import rmit.se2.pkg2012a.skoorti.model.person.Person;

/**
 *
 * @author zozo
 */
public class PersonDetailView extends javax.swing.JPanel {

    private Person person;
    /**
     * Creates new form PersonDetailView
     */
    public PersonDetailView() {
        initComponents();
        this.setVisible(false);
    }

    public Person getPerson() {
        return person;
    }

    public void setPerson(Person person) {
        this.person = person;
    }
    
    public void renderPerson() {
        if (this.person == null) {
            this.setVisible(false);
        } else {
            this.setVisible(true);
            jTextArea1.setText(person.toString());
            this.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personDetailPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        personDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Person Detail"));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        org.jdesktop.layout.GroupLayout personDetailPanelLayout = new org.jdesktop.layout.GroupLayout(personDetailPanel);
        personDetailPanel.setLayout(personDetailPanelLayout);
        personDetailPanelLayout.setHorizontalGroup(
            personDetailPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
        );
        personDetailPanelLayout.setVerticalGroup(
            personDetailPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, personDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
        );

        add(personDetailPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel personDetailPanel;
    // End of variables declaration//GEN-END:variables
}
