/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rmit.se2.pkg2012a.skoorti.view.panel;

import java.util.List;
import rmit.se2.pkg2012a.skoorti.model.research.Research;

/**
 *
 * @author zozo
 */
public class ResearchListView extends javax.swing.JPanel {

    private List<Research> researchList;
    /**
     * Creates new form ResearchListView
     */
    public ResearchListView(List<Research> researchList) {
        initComponents();
        this.setName("researchPanel");
        this.setResearchList(researchList);
    }

    public List<Research> getResearchList() {
        return researchList;
    }

    public void setResearchList(List<Research> researchList) {
        this.researchList = researchList;
        if (researchList != null) {
            this.researchList = researchList;
            this.jPanel1.removeAll();
            for (Research r : researchList) {
                ResearchView view = new ResearchView(r);
                this.jPanel1.add(view);
            }
            this.jPanel1.revalidate();
            this.jPanel1.repaint();
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
