/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rmit.se2.pkg2012a.skoorti.view.panel;

import java.util.Observable;
import java.util.Observer;
import rmit.se2.pkg2012a.skoorti.GameEngine;
import rmit.se2.pkg2012a.skoorti.model.util.Mediator;
import rmit.se2.pkg2012a.skoorti.model.person.Person;

/**
 *
 * @author zozo
 */
public class StatusPanel extends javax.swing.JPanel {
    private GameEngine gameEngine;
    private PersonDetailView personDetailView;
    /**
     * Creates new form StatusPanel
     */
    public StatusPanel(final GameEngine gameEngine) {
        initComponents();
        this.gameEngine = gameEngine;
        this.animalLabel.setText(String.valueOf(gameEngine.getNumberAnimal()));
        this.buildingLabel.setText(String.valueOf(gameEngine.getNumberBuilding()));
        this.researchLabel.setText(String.valueOf(gameEngine.getNumberCompletedResearch()));
        this.visitorLabel.setText(String.valueOf(gameEngine.getNumberVisitor()));
        this.moneyLabel.setText(String.valueOf(gameEngine.getBudget()));
        personDetailView = new PersonDetailView();
        this.add(personDetailView);
        riskValue.setText("0/" + gameEngine.getGameStrategy().getMaxRisk());
        escapeCount.setText(String.valueOf(gameEngine.getAnimalEscape()));
        
        
        Mediator.subscribe("status:building", new Observer(){

            @Override
            public void update(Observable o, Object o1) {
                buildingLabel.setText(String.valueOf(gameEngine.getNumberBuilding()));
            }
            
        });
        
        Mediator.subscribe("status:personDetail", new Observer(){

            @Override
            public void update(Observable o, Object o1) {
                personDetailView.setPerson((Person)o1);
                personDetailView.renderPerson();
            }
            
        });
        
        Mediator.subscribe("status:budget", new Observer(){

            @Override
            public void update(Observable o, Object o1) {
                moneyLabel.setText(String.valueOf(o1));
            }
            
        });
        
        Mediator.subscribe("status:animal", new Observer(){

            @Override
            public void update(Observable o, Object o1) {
                animalLabel.setText(String.valueOf(gameEngine.getNumberAnimal()));
            }
            
        });
        
        Mediator.subscribe("status:research", new Observer(){

            @Override
            public void update(Observable o, Object o1) {
                researchLabel.setText(String.valueOf(gameEngine.getNumberCompletedResearch()));
            }
            
        });
        
        Mediator.subscribe("status:escape", new Observer(){

            @Override
            public void update(Observable o, Object o1) {
                escapeCount.setText(String.valueOf(gameEngine.getAnimalEscape()));
            }
            
        });
        
        Mediator.subscribe("game:visitor:change", new Observer(){

            @Override
            public void update(Observable o, Object o1) {
                visitorLabel.setText(o1.toString());
            }
        
        });
        
        Mediator.subscribe("game:risk:change", new Observer(){

            @Override
            public void update(Observable o, Object o1) {
                riskValue.setText(o1.toString() + "/" + gameEngine.getGameStrategy().getMaxRisk());
            }
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        buildingLabel = new javax.swing.JLabel();
        animalLabel = new javax.swing.JLabel();
        researchLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        moneyLabel = new javax.swing.JLabel();
        visitorLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        riskValue = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        escapeCount = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        buildingLabel.setText("jLabel8");

        animalLabel.setText("jLabel10");

        researchLabel.setText("jLabel9");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Current Money: ");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Visitors: ");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Buildings: ");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("Completed researches: ");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("Animals: ");

        moneyLabel.setText("jLabel6");

        visitorLabel.setText("jLabel7");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setText("Risk: ");

        riskValue.setText("0");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setText("Escapes:");

        escapeCount.setText("jLabel8");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(moneyLabel))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(buildingLabel))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel4)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(jLabel5)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(animalLabel)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(researchLabel))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(visitorLabel))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(riskValue))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel7)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(escapeCount)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(moneyLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(visitorLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(buildingLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(researchLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(animalLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(riskValue))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(escapeCount))
                .addContainerGap())
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 266, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 289, Short.MAX_VALUE)
        );

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel animalLabel;
    private javax.swing.JLabel buildingLabel;
    private javax.swing.JLabel escapeCount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel moneyLabel;
    private javax.swing.JLabel researchLabel;
    private javax.swing.JLabel riskValue;
    private javax.swing.JLabel visitorLabel;
    // End of variables declaration//GEN-END:variables

    
}
